# If use_dark_mode is set to True the main color for the main body of the mandelbrot set
# is set to black. Else it is white.
use_dark_mode: True

# The width of the image.
# Default 1920
width: 1000

# The height of the image.
# Default 1080
height: 1000

# The higher the value the more details. Causes slower calculations.
# Default 512
max_iterations: 1024*10

# The resolution of the image. The slower the value the more zoomed in.
# Default 1.5
# Limit     0.00000000000001
resolution: 1.5

# ! All directions are for the virtual "camera" !

# The center of the viewport on the x axis. Negative values are to the left.
# Default -.5
center_x: -.5

# The center of the viewport on the y axis. Negative values are up.
# Default 0
center_y: 0

# Use color or not
# Default True
use_color: True

# The profile ignores the above values and uses predefined values instead.
# If set to -1 it is disabled
use_profile: -1

# Profile -1: DISABLED
# Profile 0: DEFAULT
# Profile 1: Small version
# Profile 2: Spirals


# Color must be on
# Profile must be -1
do_animation: True
target_center_x: -0.7765929020241705
target_center_y: -0.13664090727687
target_resolution: 0.00000000000001
target_frames: 300
target_frame_rate: 15
should_make_webm: True
# Default 8000k
webm_bitrate: 22000k