# If use_dark_mode is set to True the main color for the main body of the mandelbrot set
# is set to black. Else it is white.
use_dark_mode: True

# The width of the image.
# Default 1920
width: 1920

# The height of the image.
# Default 1080
height: 1080

# The higher the value the more details. Causes slower calculations.
# Default 512
max_iterations: 1024*5

# The resolution of the image. The slower the value the more zoomed in.
# Default 1.5
resolution: 0.0001

# ! All directions are for the virtual "camera" !

# The center of the viewport on the x axis. Negative values are to the left.
# Default -.5
center_x: -.717

# The center of the viewport on the y axis. Negative values are up.
# Default 0
center_y: -0.2498

# Use color or not
# Default True
use_color: True

# The profile ignores the above values and uses predefined values instead.
# If set to -1 it is disabled
use_profile: 0

# Profile -1: DISABLED
# Profile 0: DEFAULT
# Profile 1: Small version
# Profile 2: Spirals